apiVersion: apps/v1

kind: Deployment

metadata:

  name: kubermatic-dl-deployment

spec:

  selector:

    matchLabels:

      app: kubermatic-dl

  replicas: 3

  template:

    metadata:

      labels:

        app: kubermatic-dl

    spec:

     containers:

     - name: kubermatic-dl

       image: kubermatic00/kubermatic-dl:latest

       imagePullPolicy: Always

       ports:

       - containerPort: 8080